name: テスト,ビルド

on:
  push:
    branches:
      - main
    paths:
      - 'main.py'
      - 'src/**'
      - 'test/**'
      - '.github/workflows/**'

jobs:
  uv-example:
    name: python
    strategy:
      fail-fast: true
      matrix:
        runs-on:
          - "ubuntu-20.04"
          - "ubuntu-22.04-arm"

    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4

      - name: uvインストール
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: パッケージインストール
        run: uv sync --all-extras --dev

      - name: テスト
        run: uv run python -m pytest

      - name: ビルド
        run: |
            uv run pyinstaller main.py \
              --onefile \
              --distpath ./dist

      - name: artifactのアップロード
        uses: actions/upload-artifact@v4
        with:
          name: result-artifact
          path: ./dist/main
